band_size: 8
content_key: text
local_input: /Users/mattj/work/minhash-rs/examples/simple_exact/input
output_dir: /Users/mattj/work/minhash-rs/examples/simple_exact/output
max_lines_per_path: 100
name: simple-exact-dedup
ngram_size: 5
num_bands: 14
num_docs: 1000
num_sig_chunks: 2
remote_input: UNNEEDED FOR SINGLE NODE
remote_output: UNNEEDED FOR SINGLE NODE
remote_working_dir: UNNEEDED FOR SINGLE NODE
tokenizer_str: uniseg
working_dir: /Users/mattj/work/minhash-rs/examples/simple_exact/working_rs
annotate_only: true