mode: simple

content_key: text # json key for content in the training files
local_input: fixtures/local_input
reference_input: fixtures/reference-questions
report_output_dir: fixtures/output_cl100k
cleaned_output_dir: fixtures/cleaned  # Optional: separate directory for purified files
purify: false  # Enable creation of cleaned files

ngram_size: 5  # Size of indexed n-grams scanned for question matches, I recommend an odd number :) TODO :)
sample_every_m_tokens: 10  # sample for a question match this often
max_consecutive_misses: 12 # How many misses to tolerate before short circuiting cluster expansion
min_short_answer_distance: 30 # The minimum window on either side of a question to look for an answer. max(answer_length*2, min_short_answer_distance)
exclude_question_from_answer_sweep: true # When verifying the presence of an answer, do not consider the question match itself.

simple_contamination_score_threshold: 0.8 # Contamination score threshold for SIMPLE mode (default: 0.79)

eval_min_word_count: 10  # Minimum post-cleaning word count necessary to include for eval file indexing.
punctuation_chars: "!’\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~”“"  # (uses default if not specified)
tokenizer_str: cl100k # cl100k, p50k

# worker_threads: 8  # Number of worker threads for daemon mode, controls downloads. Defaults to available cpus.
# toxic_overlap_threshold: 0.8 # Documents below this will not be considered. THIS IS HARDCODED AT 80%. Considering removal. Dead option...but maybe comes back?

