mode: simple

content_key: text
local_input: /home/robert/Downloads/export-test
reference_input: fixtures/reference
report_output_dir: fixtures/output
cleaned_output_dir: fixtures/cleaned

tokenizer_str: word
ngram_size: 4
question_threshold: 0.8
max_consecutive_misses: 8
answer_threshold: 0.8
min_short_answer_distance: 30

# Reference preprocessing options
eval_dedup: false  # Enable exact deduplication of reference entries
eval_min_token_length: 0  # Minimum token count for reference entries (0 = disabled)
eval_min_unique_word_count: 0  # Minimum unique word count for reference entries (0 = disabled)

punctuation_chars: "!’\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~”“‘’"  # (uses default if not specified)
