mode: simple

content_key: text
local_input: /home/robert/Downloads/export-test
reference_input: fixtures/reference-questions-and-answers
report_output_dir: fixtures/output
cleaned_output_dir: fixtures/cleaned_test
purify: true

tokenizer_str: word
ngram_size: 4
question_threshold: 0.8
max_consecutive_misses: 8
answer_threshold: 0.8
min_short_answer_distance: 30

eval_min_token_count: 10
punctuation_chars: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~”“’"
