mode: simple

content_key: text
local_input: fixtures/local_input
reference_input: fixtures/reference-questions
report_output_dir: fixtures/output
cleaned_output_dir: fixtures/cleaned
purify: false

tokenizer_str: word
ngram_size: 4
simple_contamination_score_threshold: 0.8
max_consecutive_misses: 8
min_short_answer_distance: 30

eval_min_token_count: 10
punctuation_chars: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~”“’"
